on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

name: cloudrun-deploy and security scanning

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE: vuln-image
  PROFILE: prod

jobs:
  full_pipeline:
    name: Full Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: configure_gcloud
      name: Configure gcloud CLI
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth configure-docker europe-docker.pkg.dev --quiet
        gcloud components install docker-credential-gcr --quiet

    - name: Generate Build ID
      id: prep
      run: |
        env=prod
        sha=${GITHUB_SHA::8}
        ts=$(date +%Y%m%d%H%M%S)
        echo "::set-output name=BUILD_ID::${env}-${ts}-${sha}"

    - name: Debug Directory
      run: ls -al

    - name: Build and Push Docker Image
      id: build
      run: |-
        gcloud auth configure-docker europe-docker.pkg.dev --quiet
        GCR_IMAGE=us-central1-docker.pkg.dev/absolute-advice-442515-h8/docker-repo/dvwa:latest
        docker build -f Dockerfile . --tag $GCR_IMAGE
        docker push $GCR_IMAGE
        echo "::set-output name=image::$GCR_IMAGE"

    - name: Run Snyk Test
      continue-on-error: true
      run: |-
        npm install snyk -g
        snyk auth 5db83b3a-a352-480d-9a97-e7a7af955133
        snyk code test

    - name: Deploy to Cloud Run
      run: |-
        gcloud config set project $PROJECT_ID
        gcloud config set run/region us-central1
        gcloud run deploy vuln-image \
          --image=${{ steps.build.outputs.image }} \
          --platform managed \
          --allow-unauthenticated

    - name: Set Up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Check Java Version
      run: java -version

    - name: Run HawkScan
      uses: stackhawk/hawkscan-action@v2.2.0
      with:
        apiKey: hawk.5db83b3a-a352-480d-9a97-e7a7af955133
