on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

name: cloudrun-deploy and security scanning

env:
  PROJECT_ID: ${{ secrets.GCP_CREDENTIALS }}
  IMAGE: vuln-image
  PROFILE: prod

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    permissions:
      id-token: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate to GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Configure Docker Auth
      run: |-
        gcloud auth configure-docker

    - name: Generate build ID
      id: prep
      run: |
        env=prod
        sha=${GITHUB_SHA::8}
        ts=$(date +%Y%m%d%H%M%S)
        echo "BUILD_ID=${env}-${ts}-${sha}" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |-
        GCR_IMAGE=gcr.io/$PROJECT_ID/$IMAGE
        docker build . --tag $GCR_IMAGE
        docker push $GCR_IMAGE
        echo "image=$GCR_IMAGE" >> $GITHUB_ENV
        
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set project $PROJECT_ID
        gcloud config set run/region us-central1
        gcloud run deploy $IMAGE --image=$image \
          --platform managed \
          --allow-unauthenticated

    - name: Snyk Test
      continue-on-error: true
      run: |
        npm install snyk -g
        snyk auth c64046ce-9e36-4baf-b969-1385037a5c22
        snyk code test

    - name: Run HawkScan
      uses: stackhawk/hawkscan-action@v2.2.0
      with: 
        apiKey: ${{ secrets.HAWK_API_KEY }}
