on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

name: cloudrun-deploy and security scanning

env:
  PROJECT_ID: absolute-advice-442515-h8
  IMAGE: vuln-image
  PROFILE: prod
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    permissions:
      id-token: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        id: build
        run: |-
          GCR_IMAGE=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-repo/${{ env.IMAGE }}:latest
          docker build . --tag $GCR_IMAGE
          docker push $GCR_IMAGE
          echo "GCR_IMAGE=$GCR_IMAGE" >> $GITHUB_ENV

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |-
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set run/region us-central1
          gcloud run deploy ${{ env.IMAGE }} \
            --image=$GCR_IMAGE \
            --platform managed \
            --allow-unauthenticated
